version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    groups:
      github-actions:
        patterns:
          - "actions/*"
          - "ruby/setup-ruby"
          - "Homebrew/actions/*"
    commit-message:
      prefix: "ci"
      include: "scope"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    groups:
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "rubocop*"
          - "rspec*"
    commit-message:
      prefix: "deps"
      include: "scope"
