repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: local
    hooks:
      - id: rubocop
        name: RuboCop
        entry: bundle exec rubocop
        language: system
        types: [ruby]
        pass_filenames: true
        require_serial: true
        args: ["--force-exclusion", "--autocorrect"]
        exclude: ^(docs/|vendor/|bin/|tmp/|\.git/|node_modules/)
      - id: brew-style
        name: Brew Style
        entry: brew style --fix
        language: system
        types: [ruby]
        pass_filenames: false
        require_serial: true
        exclude: ^(docs/|vendor/|bin/|tmp/|\.git/|node_modules/)

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        args: ["--severity=warning"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [css, javascript, json, yaml]
        exclude: "^docs/"
