AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'docs/**/*'
    - '.bundle/**/*'

Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '^\s*#'
    - 'url "'

Layout/IndentationStyle:
  EnforcedStyle: spaces

Layout/IndentationWidth:
  Width: 2

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Naming/FileName:
  Exclude:
    - 'Formula/**/*.rb'

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'
