# frozen_string_literal: true

# a@1.0.0 — generated by scripts/sync_formulae.rb; do not edit by hand.
class AAT100 < Formula
  desc "Encrypt and decrypt files with your SSH keys using the age format"
  homepage "https://github.com/ivuorinen/a"
  version "1.0.0"
  license "MIT"
  keg_only :versioned_formula

  on_macos do
    on_arm do
      url "https://github.com/ivuorinen/a/releases/download/v1.0.0/a_1.0.0_darwin_arm64.tar.gz"
      sha256 "d84d01bf4d693069619fe5ce98e050036bd352f0966126c9d58d5c176529dea0"
    end
    on_intel do
      url "https://github.com/ivuorinen/a/releases/download/v1.0.0/a_1.0.0_darwin_amd64.tar.gz"
      sha256 "5b0b62282643a6d4ad4d856058d67fa8b9f7021edf5280690ad3be50e9c70a65"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ivuorinen/a/releases/download/v1.0.0/a_1.0.0_linux_arm64.tar.gz"
      sha256 "364d17150b7ac35eb6ef43ca5d9b0f9ead75d619b6600f26d1dbb297c6d6041b"
    end
    on_intel do
      url "https://github.com/ivuorinen/a/releases/download/v1.0.0/a_1.0.0_linux_amd64.tar.gz"
      sha256 "03b0577b41923d152f36df23460ffe171e1d7095f6e5929004c006999cadddaf"
    end
  end

  def install
    bin.install "a"
  end

  test do
    system bin/"a", "--help"
  end
end
