# frozen_string_literal: true

# pinboard-checker — generated by scripts/sync_formulae.rb; do not edit by hand.
# released: 2026-08-29T00:57:10Z
class PinboardChecker < Formula
  desc "CLI app for checking alive bookmarks and unrolling shorturls"
  homepage "https://github.com/ivuorinen/pinboard-checker"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/ivuorinen/pinboard-checker/releases/download/v0.1.0/pinboard-checker_0.1.0_darwin_arm64.tar.gz"
      sha256 "4cb3fa7b1dc7a439271f52688d0e93fd8a9c102bed7d841989e5f893f4e71c06"
    end
    on_intel do
      url "https://github.com/ivuorinen/pinboard-checker/releases/download/v0.1.0/pinboard-checker_0.1.0_darwin_amd64.tar.gz"
      sha256 "9e6d454d8c366bafbd8882bfc67abb0b576d13d72686389fcb5a4fca45f0d5e8"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ivuorinen/pinboard-checker/releases/download/v0.1.0/pinboard-checker_0.1.0_linux_arm64.tar.gz"
      sha256 "62eff1b764575f72b6484ddefb5351cf489a153b720873ea2b21a4713aaad677"
    end
    on_intel do
      url "https://github.com/ivuorinen/pinboard-checker/releases/download/v0.1.0/pinboard-checker_0.1.0_linux_amd64.tar.gz"
      sha256 "f9e473aec12eb84efd055ff271822a838019b4c80ec856573b00f84b1065792f"
    end
  end

  def install
    bin.install "pinboard-checker"
  end

  test do
    system bin/"pinboard-checker", "--help"
  end
end
