# frozen_string_literal: true

# gh-action-readme — generated by scripts/sync_formulae.rb; do not edit by hand.
class GhActionReadme < Formula
  desc "Generate documentation for GitHub Actions with themes and multiple formats"
  homepage "https://github.com/ivuorinen/gh-action-readme"
  version "1.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/ivuorinen/gh-action-readme/releases/download/v1.1.0/gh-action-readme_Darwin_arm64.tar.gz"
      sha256 "0bf1e05de9b2db19bfc93ca49b555bd7cd3032bdc71d971e2f115bba0da61987"
    end
    on_intel do
      url "https://github.com/ivuorinen/gh-action-readme/releases/download/v1.1.0/gh-action-readme_Darwin_x86_64.tar.gz"
      sha256 "c37987025d23d9b3077c51f0faad4c2847fbed20c2cfbd5d9995e9c5ad0ef093"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ivuorinen/gh-action-readme/releases/download/v1.1.0/gh-action-readme_Linux_arm64.tar.gz"
      sha256 "20c6e55ad9d86b9f1cd8bfe3c9500dfcc93b717b9627e633e4cbed804583558b"
    end
    on_intel do
      url "https://github.com/ivuorinen/gh-action-readme/releases/download/v1.1.0/gh-action-readme_Linux_x86_64.tar.gz"
      sha256 "e1f6dfb546e896a2124c6f6bb4972e46358340120620c6608606d3728d35e96b"
    end
  end

  def install
    bin.install "gh-action-readme"
  end

  test do
    system bin/"gh-action-readme", "--help"
  end
end
