# frozen_string_literal: true

# gh-action-readme@0.3.0 — generated by scripts/sync_formulae.rb; do not edit by hand.
class GhActionReadmeAT030 < Formula
  desc "Generate documentation for GitHub Actions with themes and multiple formats"
  homepage "https://github.com/ivuorinen/gh-action-readme"
  version "0.3.0"
  license "MIT"
  keg_only :versioned_formula

  on_macos do
    on_arm do
      url "https://github.com/ivuorinen/gh-action-readme/archive/refs/tags/v0.3.1.tar.gz"
      sha256 "7473ac543aef54f7270b2a8b820d73c272009878dc80dcbb5053d2185885d945"
    end
    on_intel do
      url "https://github.com/ivuorinen/gh-action-readme/releases/download/v0.3.0/gh-action-readme_Darwin_x86_64.tar.gz"
      sha256 "d729ef8225dfc7567c6b18772288bc64f062d5e410591f9c1f326c4d21577b26"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ivuorinen/gh-action-readme/releases/download/v0.3.0/gh-action-readme_Linux_arm64.tar.gz"
      sha256 "78c370aad96b90915cdbc43f608f17d359ca22e81ee5c56ac532b43e218f0ad5"
    end
    on_intel do
      url "https://github.com/ivuorinen/gh-action-readme/releases/download/v0.3.0/gh-action-readme_Linux_x86_64.tar.gz"
      sha256 "94be72479421bfe55396535b3e04ffacf5f00a90563b9453ab4931bd2842b0c5"
    end
  end

  def install
    bin.install "gh-action-readme"
  end

  test do
    system bin/"gh-action-readme", "--help"
  end
end
