# frozen_string_literal: true

# gh-action-readme@1.0.0 — generated by scripts/sync_formulae.rb; do not edit by hand.
class GhActionReadmeAT100 < Formula
  desc "Generate documentation for GitHub Actions with themes and multiple formats"
  homepage "https://github.com/ivuorinen/gh-action-readme"
  version "1.0.0"
  license "MIT"
  keg_only :versioned_formula

  on_macos do
    on_arm do
      url "https://github.com/ivuorinen/gh-action-readme/archive/refs/tags/v1.1.0.tar.gz"
      sha256 "80e944659a5d310ba4b850e746f3814ead7aa3b4d7d5b37c5c7dceb9163b8c80"
    end
    on_intel do
      url "https://github.com/ivuorinen/gh-action-readme/releases/download/v1.0.0/gh-action-readme_Darwin_x86_64.tar.gz"
      sha256 "164df6b9acdef2f45e7510dd4beb36fcc9e37c6166dd612ea68ceff1e5fb55e9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ivuorinen/gh-action-readme/releases/download/v1.0.0/gh-action-readme_Linux_arm64.tar.gz"
      sha256 "3622add37cbf136d9346c023f814a117dcbcb0d82e570e5ce06018d0a1879c47"
    end
    on_intel do
      url "https://github.com/ivuorinen/gh-action-readme/releases/download/v1.0.0/gh-action-readme_Linux_x86_64.tar.gz"
      sha256 "fead70168b186069151e1c159ef08db05dc050d72982a631f03458588ef22af2"
    end
  end

  def install
    bin.install "gh-action-readme"
  end

  test do
    system bin/"gh-action-readme", "--help"
  end
end
