# frozen_string_literal: true

# gh-action-readme@0.3.1 — generated by scripts/sync_formulae.rb; do not edit by hand.
class GhActionReadmeAT031 < Formula
  desc "Generate documentation for GitHub Actions with themes and multiple formats"
  homepage "https://github.com/ivuorinen/gh-action-readme"
  version "0.3.1"
  license "MIT"
  keg_only :versioned_formula

  on_macos do
    on_arm do
      url "https://github.com/ivuorinen/gh-action-readme/archive/refs/tags/v1.1.0.tar.gz"
      sha256 "80e944659a5d310ba4b850e746f3814ead7aa3b4d7d5b37c5c7dceb9163b8c80"
    end
    on_intel do
      url "https://github.com/ivuorinen/gh-action-readme/releases/download/v0.3.1/gh-action-readme_Darwin_x86_64.tar.gz"
      sha256 "2d6518882d59c18a14a5cee7c0b0a9c72f605c4e2c64f909e292a685a81b4da6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ivuorinen/gh-action-readme/releases/download/v0.3.1/gh-action-readme_Linux_arm64.tar.gz"
      sha256 "e4a6acaf99bb642da367d123e7ecc92aeedc22f4ef1530c69ef53ecb5d40620c"
    end
    on_intel do
      url "https://github.com/ivuorinen/gh-action-readme/releases/download/v0.3.1/gh-action-readme_Linux_x86_64.tar.gz"
      sha256 "848f5ef558f1181a15d807b1178f17c9ef811c61c45874721265df6a0a4a751d"
    end
  end

  def install
    bin.install "gh-action-readme"
  end

  test do
    system bin/"gh-action-readme", "--help"
  end
end
