# frozen_string_literal: true

# gh-calver@0.1.0 — generated by scripts/sync_formulae.rb; do not edit by hand.
class GhCalverAT010 < Formula
  desc "GitHub CLI calver command"
  homepage "https://github.com/ivuorinen/gh-calver"
  version "0.1.0"
  license "MIT"
  keg_only :versioned_formula

  on_macos do
    on_arm do
      url "https://github.com/ivuorinen/gh-calver/releases/download/v0.1.0/gh-calver_Darwin_arm64.tar.gz"
      sha256 "b3d10b95954d984911740d2674980066b647d894e512822e8f5318f77a4df4fe"
    end
    on_intel do
      url "https://github.com/ivuorinen/gh-calver/releases/download/v0.1.0/gh-calver_Darwin_x86_64.tar.gz"
      sha256 "ed1532cffd90fc584cbe27d07ddf38047c845326b886fe017ee0d68a869c7d22"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ivuorinen/gh-calver/releases/download/v0.1.0/gh-calver_Linux_arm64.tar.gz"
      sha256 "a9cb0e5c12da08359efe24d010f69086bbe9c28ab83ab055c3eca69c5fd67509"
    end
    on_intel do
      url "https://github.com/ivuorinen/gh-calver/releases/download/v0.1.0/gh-calver_Linux_x86_64.tar.gz"
      sha256 "9678007f70e6908fe67d076db1144dd1c32b2acf03af82e8cc94a721897fe35f"
    end
  end

  def install
    bin.install "gh-calver"
  end

  test do
    system bin/"gh-calver", "--help"
  end
end
