# frozen_string_literal: true

# gh-calver@2026.03.1 — generated by scripts/sync_formulae.rb; do not edit by hand.
class GhCalverAT2026031 < Formula
  desc "GitHub CLI calver command"
  homepage "https://github.com/ivuorinen/gh-calver"
  version "2026.03.1"
  license "MIT"
  keg_only :versioned_formula

  on_macos do
    on_arm do
      url "https://github.com/ivuorinen/gh-calver/releases/download/2026.03.1/gh-calver_darwin_arm64"
      sha256 "c416a40d03fdb1163c59e51688bcdf7bd648f1941bf3bf3a53db25cb3c8dd479"
    end
    on_intel do
      url "https://github.com/ivuorinen/gh-calver/releases/download/2026.03.1/gh-calver_darwin_amd64"
      sha256 "bc66b2d7bb17e07addbd392361b7d1faf0dd28a06f9e0bd31592a214466da56d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ivuorinen/gh-calver/releases/download/2026.03.1/gh-calver_linux_arm64"
      sha256 "f1711e1167dfd1e3c0ecbbaca955c8857f0c2ad51b619f8dc0d6c923fe18d64a"
    end
    on_intel do
      url "https://github.com/ivuorinen/gh-calver/releases/download/2026.03.1/gh-calver_linux_amd64"
      sha256 "033d34f2d4e1ab03444a622b895eb16cbeeec3be03086626a0637f56d1b4c69e"
    end
  end

  def install
    bin.install File.basename(stable.url) => "gh-calver"
  end

  test do
    system bin/"gh-calver", "--help"
  end
end
