# frozen_string_literal: true

# gh-calver@2026.03.4 — generated by scripts/sync_formulae.rb; do not edit by hand.
class GhCalverAT2026034 < Formula
  desc "GitHub CLI calver command"
  homepage "https://github.com/ivuorinen/gh-calver"
  version "2026.03.4"
  license "MIT"
  keg_only :versioned_formula

  on_macos do
    on_arm do
      url "https://github.com/ivuorinen/gh-calver/releases/download/2026.03.4/gh-calver_darwin-arm64"
      sha256 "3bf76a07abb90b165010d61779bfd1f514ce3d3e656896a3699855a2724ef45c"
    end
    on_intel do
      url "https://github.com/ivuorinen/gh-calver/releases/download/2026.03.4/gh-calver_darwin-amd64"
      sha256 "07a66364db807c8513864e731fd7d74333c66ff734e8a5f616a9a7e6ead1f1aa"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ivuorinen/gh-calver/releases/download/2026.03.4/gh-calver_linux-arm64"
      sha256 "5bbfaa5cabf374fa7794d4af03ccd63cb6f9c99e698635ec9d10f18511b91810"
    end
    on_intel do
      url "https://github.com/ivuorinen/gh-calver/releases/download/2026.03.4/gh-calver_linux-amd64"
      sha256 "4de8519c99f041e743efb974687326f99a22421a35455bc18bc3b770fac70a45"
    end
  end

  def install
    bin.install File.basename(stable.url) => "gh-calver"
  end

  test do
    system bin/"gh-calver", "--help"
  end
end
