# frozen_string_literal: true

# gh-calver@2026.03.0 — generated by scripts/sync_formulae.rb; do not edit by hand.
class GhCalverAT2026030 < Formula
  desc "GitHub CLI calver command"
  homepage "https://github.com/ivuorinen/gh-calver"
  version "2026.03.0"
  license "MIT"
  keg_only :versioned_formula

  on_macos do
    on_arm do
      url "https://github.com/ivuorinen/gh-calver/releases/download/2026.03.0/gh-calver_darwin_arm64.tar.gz"
      sha256 "fe0d8be6922570eaff987f3428debac754f526eecaaf65e2c1240aabc0cf920d"
    end
    on_intel do
      url "https://github.com/ivuorinen/gh-calver/releases/download/2026.03.0/gh-calver_darwin_amd64.tar.gz"
      sha256 "2a095689f28cb8f06e57816371b82fdd4d0efa7336c0dbb2a13f573ba2973d16"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ivuorinen/gh-calver/releases/download/2026.03.0/gh-calver_linux_arm64.tar.gz"
      sha256 "2cbf25ae4b6686e3c4bccd61ec8ef384443fe4fca7ed8dba32cb0b9f16c93b66"
    end
    on_intel do
      url "https://github.com/ivuorinen/gh-calver/releases/download/2026.03.0/gh-calver_linux_amd64.tar.gz"
      sha256 "f3adb017d632d06dd29e45b2b2df5bd6efd432ce7a75138991e7130916f0ef64"
    end
  end

  def install
    bin.install "gh-calver"
  end

  test do
    system bin/"gh-calver", "--help"
  end
end
