# frozen_string_literal: true

# gh-calver@2026.03.2 — generated by scripts/sync_formulae.rb; do not edit by hand.
class GhCalverAT2026032 < Formula
  desc "GitHub CLI calver command"
  homepage "https://github.com/ivuorinen/gh-calver"
  version "2026.03.2"
  license "MIT"
  keg_only :versioned_formula

  on_macos do
    on_arm do
      url "https://github.com/ivuorinen/gh-calver/releases/download/2026.03.2/gh-calver_darwin-arm64"
      sha256 "0203d3db09bb93a3b47ad107b95991176fdf470d1442910fb0e28aa2f7c0b017"
    end
    on_intel do
      url "https://github.com/ivuorinen/gh-calver/releases/download/2026.03.2/gh-calver_darwin-amd64"
      sha256 "67194b6c03fd282d040248ad6f39e7ab42140b315719f7d8b8721fc9383a80ee"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ivuorinen/gh-calver/releases/download/2026.03.2/gh-calver_linux-arm64"
      sha256 "22715a72e4cecaf2a0078281765064b4c73126b2367c421a134255a7c49a2ba2"
    end
    on_intel do
      url "https://github.com/ivuorinen/gh-calver/releases/download/2026.03.2/gh-calver_linux-amd64"
      sha256 "7d1e3552bf431cb5ed18744ed53e4b9a9912ef75c3b0987355a8ec5f91d05d4a"
    end
  end

  def install
    bin.install File.basename(stable.url) => "gh-calver"
  end

  test do
    system bin/"gh-calver", "--help"
  end
end
