# frozen_string_literal: true

# gh-history@2026.03.0 — generated by scripts/sync_formulae.rb; do not edit by hand.
class GhHistoryAT2026030 < Formula
  desc "GitHub CLI history command"
  homepage "https://github.com/ivuorinen/gh-history"
  version "2026.03.0"
  license "MIT"
  keg_only :versioned_formula

  on_macos do
    on_arm do
      url "https://github.com/ivuorinen/gh-history/releases/download/2026.03.0/gh-history_darwin-arm64"
      sha256 "bc13de419d4cd0c650fe08ffe0840b25c37efc8c369d91f1aabedd881279ceb4"
    end
    on_intel do
      url "https://github.com/ivuorinen/gh-history/releases/download/2026.03.0/gh-history_darwin-amd64"
      sha256 "32ec9704a18bcd7eb67cfce7e4c4d35f0f855ffd234598e683dc06cad1fa8a28"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ivuorinen/gh-history/releases/download/2026.03.0/gh-history_linux-arm64"
      sha256 "eb6977b977db7274ca468fcdaa0bfe1d72a218c060809ae967f03b5dde33f501"
    end
    on_intel do
      url "https://github.com/ivuorinen/gh-history/releases/download/2026.03.0/gh-history_linux-amd64"
      sha256 "7ac0be1e3dc9025feb22ae273ff34665f77eb530b8897e11c2360eb97412b981"
    end
  end

  def install
    bin.install File.basename(stable.url) => "gh-history"
  end

  test do
    system bin/"gh-history", "--help"
  end
end
