#!/usr/bin/env ruby
# frozen_string_literal: true

# Pull-based formula generator.
#
# Reads formula-sources.json, asks the GitHub API (via `gh`) for each repo's
# latest release + metadata, matches the prebuilt binary assets to Homebrew's
# platforms, and (re)writes Formula/<x>/<name>.rb. sha256 comes from the API's
# per-asset `digest` field, so nothing is downloaded.
#
# `gh` is used for auth (GH_TOKEN / gh auth) and is present on the CI runner.

require "json"
require "open3"
require "fileutils"

module SyncFormulae
  ROOT        = File.expand_path("..", __dir__)
  FORMULA_DIR = File.join(ROOT, "Formula")
  SOURCES     = File.join(ROOT, "formula-sources.json")

  # Homebrew platforms we target, each with the regexes that identify its asset.
  # arm/intel regexes are mutually exclusive so a darwin_amd64 asset never
  # matches the arm slot and vice versa.
  PLATFORMS = [
    { os: "macos", arch: "arm",   os_re: /darwin|macos/i, arch_re: /arm64|aarch64/i },
    { os: "macos", arch: "intel", os_re: /darwin|macos/i, arch_re: /amd64|x86_64|x64/i },
    { os: "linux", arch: "arm",   os_re: /linux/i,        arch_re: /arm64|aarch64/i },
    { os: "linux", arch: "intel", os_re: /linux/i,        arch_re: /amd64|x86_64|x64/i },
  ].freeze

  # Sidecar/packaging assets and out-of-scope platforms that must never be
  # selected as the binary for a platform.
  EXCLUDE_EXT  = /\.(sbom\.json|json|deb|rpm|apk|sig|pem|txt|bundle|zip|exe|msi|asc)\z/i
  EXCLUDE_WORD = /(?:\A|[_.-])(?:windows|freebsd|386|i386)(?:[_.-]|\z)/i

  module_function

  # "gh-action-readme" -> "GhActionReadme", "a" -> "A".
  # Must round-trip through the docs parser's convert_class_name_to_formula_name.
  def class_name(name)
    name.split(/[-_]/).map { |part| part.empty? ? "" : part[0].upcase + part[1..].to_s }.join
  end

  # Homebrew `desc` must be <=80 chars, not start with an article, and not end
  # with a period (brew audit). Best-effort; override via config `desc`.
  def sanitize_desc(str)
    s = str.to_s.strip.gsub(/\s+/, " ")
    s = s.sub(/\A(?:a|an|the)\s+/i, "")
    s = s.sub(/\.\z/, "")
    s = s[0].upcase + s[1..].to_s unless s.empty?
    if s.length > 80
      s = s[0, 80]
      s = s.sub(/\s+\S*\z/, "") if s.include?(" ")
    end
    s
  end

  def excluded?(name)
    name.match?(EXCLUDE_EXT) || name.match?(EXCLUDE_WORD)
  end

  # Pick the best asset for a platform: prefer a .tar.gz archive, else a raw
  # binary. Returns { name:, url:, sha256:, archive: } or nil if absent.
  def match_asset(assets, platform)
    candidates = assets.reject { |a| excluded?(a["name"]) }
                       .select { |a| a["name"].match?(platform[:os_re]) && a["name"].match?(platform[:arch_re]) }
    chosen = candidates.find { |a| a["name"].end_with?(".tar.gz") } || candidates.first
    return nil unless chosen

    { name: chosen["name"], url: chosen["browser_download_url"],
      sha256: digest_sha256(chosen["digest"]), archive: chosen["name"].end_with?(".tar.gz") }
  end

  def digest_sha256(digest)
    m = digest.to_s.match(/\Asha256:([a-f0-9]{64})\z/i)
    raise "asset digest is not sha256: #{digest.inspect}" unless m

    m[1].downcase
  end

  # meta: name, class, desc, homepage, version, license (nil ok), bin, test,
  #       platforms => [{ os_dsl_arch..., url, sha256 }], archive (bool)
  def formula_body(meta)
    lines = []
    lines << "# frozen_string_literal: true"
    lines << ""
    lines << "# #{meta[:name]} — generated by scripts/sync_formulae.rb; do not edit by hand."
    lines << "class #{meta[:class]} < Formula"
    lines << %(  desc "#{meta[:desc]}")
    lines << %(  homepage "#{meta[:homepage]}")
    lines << %(  version "#{meta[:version]}")
    lines << %(  license "#{meta[:license]}") if meta[:license]
    lines << ""
    lines.concat(platform_blocks(meta[:platforms]))
    lines << ""
    lines << "  def install"
    lines << if meta[:archive]
               %(    bin.install "#{meta[:bin]}")
             else
               # raw binary: staged filename == the platform's asset name
               %(    bin.install File.basename(stable.url) => "#{meta[:bin]}")
             end
    lines << "  end"
    lines << ""
    lines << "  test do"
    lines << "    #{meta[:test]}"
    lines << "  end"
    lines << "end"
    "#{lines.join("\n")}\n"
  end

  # Render the on_macos/on_linux -> on_arm/on_intel nest, omitting absent slots.
  def platform_blocks(platforms)
    by_os = platforms.group_by { |p| p[:os] }
    blocks = %w[macos linux].filter_map do |os|
      slots = by_os[os]
      next unless slots

      lines = ["  on_#{os} do"]
      %w[arm intel].each do |arch|
        slot = slots.find { |p| p[:arch] == arch }
        next unless slot

        lines << "    on_#{arch} do"
        lines << %(      url "#{slot[:url]}")
        lines << %(      sha256 "#{slot[:sha256]}")
        lines << "    end"
      end
      lines << "  end"
      lines
    end
    blocks.flat_map.with_index { |b, i| i.zero? ? b : ["", *b] } # blank line between OS blocks
  end

  # ---- driver ---------------------------------------------------------------

  def gh_json(*path)
    out, err, status = Open3.capture3("gh", "api", *path)
    raise "gh api #{path.join(' ')} failed: #{err.strip}" unless status.success?

    JSON.parse(out)
  end

  def formula_path(name)
    File.join(FORMULA_DIR, name[0].downcase, "#{name}.rb")
  end

  def build_meta(source)
    repo = source["repo"]
    name = repo.split("/").last
    release = gh_json("repos/#{repo}/releases/latest")
    info    = gh_json("repos/#{repo}")

    platforms = PLATFORMS.filter_map do |p|
      asset = match_asset(release["assets"], p)
      asset && { os: p[:os], arch: p[:arch], url: asset[:url], sha256: asset[:sha256], archive: asset[:archive] }
    end
    raise "no matching binary assets for #{repo} #{release['tag_name']}" if platforms.empty?

    archives = platforms.map { |pl| pl[:archive] }.uniq
    raise "#{repo} mixes archive and raw assets; add a `bin`/override in formula-sources.json" if archives.size > 1

    {
      name:     name,
      class:    class_name(name),
      desc:     source["desc"] || sanitize_desc(info["description"]),
      homepage: "https://github.com/#{repo}",
      version:  release["tag_name"].sub(/\Av/, ""),
      license:  source["license"] || spdx(info),
      bin:      source["bin"] || name,
      test:     source["test"] || %(system bin/"#{source['bin'] || name}", "--help"),
      archive:  archives.first,
      platforms: platforms,
    }
  end

  def spdx(info)
    id = info.dig("license", "spdx_id")
    id if id && id != "NOASSERTION"
  end

  def run
    sources = JSON.parse(File.read(SOURCES))
    failures = []
    changed  = []

    sources.each do |source|
      repo = source["repo"]
      meta = build_meta(source)
      path = formula_path(meta[:name])
      body = formula_body(meta)
      old  = File.exist?(path) ? File.read(path) : nil
      if old == body
        puts "= #{repo} #{meta[:version]} (unchanged)"
        next
      end
      FileUtils.mkdir_p(File.dirname(path))
      File.write(path, body)
      verb = old ? "updated" : "created"
      old_v = old&.match(/version\s+"([^"]+)"/)&.[](1)
      changed << "#{meta[:name]}: #{old_v || '(new)'} -> #{meta[:version]}"
      puts "* #{repo} #{verb} -> #{meta[:version]} (#{meta[:platforms].size} platforms)"
    rescue StandardError => e
      # Skip this repo; its existing formula is left untouched.
      warn "! #{repo}: #{e.message}"
      failures << repo
    end

    puts changed.empty? ? "\nNo formula changes." : "\nChanged:\n#{changed.map { |c| "  #{c}" }.join("\n")}"
    unless failures.empty?
      warn "\nFailed: #{failures.join(', ')}"
      exit 1
    end
  end
end

SyncFormulae.run if __FILE__ == $PROGRAM_NAME
