#!/usr/bin/env ruby
# typed: strict
# frozen_string_literal: true

# Pull-based formula generator.
#
# Reads formula-sources.json, asks the GitHub API (via `gh`) for each repo's
# latest release + metadata, matches the prebuilt binary assets to Homebrew's
# platforms, and (re)writes Formula/<x>/<name>.rb. sha256 comes from the API's
# per-asset `digest` field, so nothing is downloaded.
#
# `gh` is used for auth (GH_TOKEN / gh auth) and is present on the CI runner.

require "json"
require "open3"
require "fileutils"

# Pull-based formula generator: reads formula-sources.json and (re)writes Formula/<x>/<name>.rb.
module SyncFormulae
  ROOT        = File.expand_path("..", __dir__).freeze
  FORMULA_DIR = File.join(ROOT, "Formula").freeze
  SOURCES     = File.join(ROOT, "formula-sources.json").freeze

  # Homebrew platforms we target, each with the regexes that identify its asset.
  # arm/intel regexes are mutually exclusive so a darwin_amd64 asset never
  # matches the arm slot and vice versa.
  PLATFORMS = [
    { os: "macos", arch: "arm",   os_re: /darwin|macos/i, arch_re: /arm64|aarch64/i },
    { os: "macos", arch: "intel", os_re: /darwin|macos/i, arch_re: /amd64|x86_64|x64/i },
    { os: "linux", arch: "arm",   os_re: /linux/i,        arch_re: /arm64|aarch64/i },
    { os: "linux", arch: "intel", os_re: /linux/i,        arch_re: /amd64|x86_64|x64/i },
  ].freeze

  # Sidecar/packaging assets and out-of-scope platforms that must never be
  # selected as the binary for a platform.
  EXCLUDE_EXT  = /\.(sbom\.json|json|deb|rpm|apk|sig|pem|txt|bundle|zip|exe|msi|asc)\z/i
  EXCLUDE_WORD = /(?:\A|[_.-])(?:windows|freebsd|386|i386)(?:[_.-]|\z)/i

  module_function

  # Homebrew Formulary.class_s-compatible name mangling:
  #   "gh-action-readme"      -> "GhActionReadme"
  #   "a"                     -> "A"
  #   "gh-calver@2026.03.4"   -> "GhCalverAT2026034"
  # Versioned formulae get brew's "@<digit>" -> "AT<digit>" rule so the docs
  # parser (which keys the formula name off the filename) and brew agree.
  def class_name(name)
    s = name.capitalize
    s = s.gsub(/[-_.\s]([a-zA-Z0-9])/) { Regexp.last_match(1).upcase }
    s = s.tr("+", "x")
    s.sub(/(.)@(\d)/, '\1AT\2')
  end

  # Homebrew `desc` must be <=80 chars, not start with an article, and not end
  # with a period (brew audit). Best-effort; override via config `desc`.
  def sanitize_desc(str)
    s = str.to_s.strip.gsub(/\s+/, " ")
    s = s.sub(/\A(?:a|an|the)\s+/i, "")
    s = s.delete_suffix(".")
    s = s[0].upcase + s[1..].to_s unless s.empty?
    if s.length > 80
      s = s[0, 80]
      s = s.sub(/\s+\S*\z/, "") if s.include?(" ")
    end
    s
  end

  def excluded?(name)
    name.match?(EXCLUDE_EXT) || name.match?(EXCLUDE_WORD)
  end

  # Pick the best asset for a platform: prefer a .tar.gz archive, else a raw
  # binary. Returns { name:, url:, sha256:, archive: } or nil if absent.
  def match_asset(assets, platform)
    candidates = assets.reject { |a| excluded?(a["name"]) }
                       .select { |a| a["name"].match?(platform[:os_re]) && a["name"].match?(platform[:arch_re]) }
    chosen = candidates.find { |a| a["name"].end_with?(".tar.gz") } || candidates.first
    return unless chosen

    { name: chosen["name"], url: chosen["browser_download_url"],
      sha256: digest_sha256(chosen["digest"]), archive: chosen["name"].end_with?(".tar.gz") }
  end

  def digest_sha256(digest)
    m = digest.to_s.match(/\Asha256:([a-f0-9]{64})\z/i)
    raise "asset digest is not sha256: #{digest.inspect}" unless m

    m[1].downcase
  end

  # meta: formula_name, class, keg_only (bool), desc, homepage, version,
  #       released_at (nil ok), license (nil ok), bin, test,
  #       platforms => [{ os, arch, url, sha256 }], archive (bool)
  def formula_body(meta)
    lines = []
    lines << "# frozen_string_literal: true"
    lines << ""
    lines << "# #{meta[:formula_name]} — generated by scripts/sync_formulae.rb; do not edit by hand."
    # Machine-readable release date for the docs site (parse_formulas reads it);
    # Homebrew ignores comments. Its version's GitHub release publish time.
    lines << "# released: #{meta[:released_at]}" if meta[:released_at]
    lines << "class #{meta[:class]} < Formula"
    lines << %Q(  desc "#{meta[:desc]}")
    lines << %Q(  homepage "#{meta[:homepage]}")
    lines << %Q(  version "#{meta[:version]}")
    lines << %Q(  license "#{meta[:license]}") if meta[:license]
    lines << "  keg_only :versioned_formula" if meta[:keg_only]
    lines << ""
    lines.concat(platform_blocks(meta[:platforms]))
    lines << ""
    lines << "  def install"
    lines << if meta[:archive]
      %Q(    bin.install "#{meta[:bin]}")
    else
      # raw binary: staged filename == the platform's asset name
      %Q(    bin.install File.basename(stable.url) => "#{meta[:bin]}")
    end
    lines << "  end"
    lines << ""
    lines << "  test do"
    lines << "    #{meta[:test]}"
    lines << "  end"
    lines << "end"
    "#{lines.join("\n")}\n"
  end

  ARCHES = %w[arm intel].freeze

  # Render the on_macos/on_linux -> on_arm/on_intel nest, omitting absent slots.
  def platform_blocks(platforms)
    by_os = platforms.group_by { |p| p[:os] }
    blocks = %w[macos linux].filter_map do |os|
      slots = by_os[os]
      next unless slots

      lines = ["  on_#{os} do"]
      ARCHES.each do |arch|
        slot = slots.find { |p| p[:arch] == arch }
        next unless slot

        lines << "    on_#{arch} do"
        lines << %Q(      url "#{slot[:url]}")
        lines << %Q(      sha256 "#{slot[:sha256]}")
        lines << "    end"
      end
      lines << "  end"
      lines
    end
    blocks.flat_map.with_index { |b, i| i.zero? ? b : ["", *b] } # blank line between OS blocks
  end

  # ---- driver ---------------------------------------------------------------

  def gh_json(*path)
    out, err, status = Open3.capture3("gh", "api", *path)
    raise "gh api #{path.join(" ")} failed: #{err.strip}" unless status.success?

    JSON.parse(out)
  end

  # Formula file for a name; the versioned suffix (name@ver) stays in the
  # filename — the first letter (before "@") picks the Formula/<x> subdir.
  def formula_path(formula_name)
    File.join(FORMULA_DIR, formula_name[0].downcase, "#{formula_name}.rb")
  end

  # Metadata for a single release's assets, or nil when the release ships no
  # matching prebuilt binaries (source-only / pre-goreleaser releases fall out
  # here, which is how old versions get skipped without a special case).
  def build_release_meta(source, name, info, release)
    version   = release["tag_name"].to_s.delete_prefix("v")
    platforms = PLATFORMS.filter_map do |p|
      asset = match_asset(release["assets"], p)
      asset && { os: p[:os], arch: p[:arch], url: asset[:url], sha256: asset[:sha256], archive: asset[:archive] }
    end
    return if platforms.empty?

    archives = platforms.map { |pl| pl[:archive] }.uniq
    raise "#{name} #{version} mixes archive and raw assets; add a `bin`/override" if archives.size > 1

    {
      name:        name,
      version:     version,
      released_at: release["published_at"],
      desc:        source["desc"] || sanitize_desc(info["description"]),
      homepage:    "https://github.com/#{source["repo"]}",
      license:     source["license"] || spdx(info),
      bin:         source["bin"] || name,
      test:        source["test"] || %Q(system bin/"#{source["bin"] || name}", "--help"),
      archive:     archives.first,
      platforms:   platforms,
    }
  end

  # All release metas for a repo, newest first. Per-release failures are logged
  # and skipped so one bad release never drops the rest.
  def build_metas(source)
    repo = source["repo"]
    name = repo.split("/").last
    info = gh_json("repos/#{repo}")
    # Newest first. Drafts are not published versions; skip them.
    # ponytail: newest 100 releases (per_page cap); add --paginate if a repo exceeds 100.
    releases = gh_json("repos/#{repo}/releases?per_page=100").reject { |r| r["draft"] }

    metas = releases.filter_map do |release|
      build_release_meta(source, name, info, release)
    rescue => e
      warn "! #{repo} #{release["tag_name"]}: #{e.message}"
      nil
    end
    raise "no releases with matching binary assets for #{repo}" if metas.empty?

    metas
  end

  # A release meta -> the formula file(s) it produces: always a keg_only
  # versioned "name@ver.rb"; the newest release also produces the plain
  # "name.rb". Versioned files need a numeric version (Homebrew "@" rule).
  def outputs_for(meta, latest:)
    files = []
    if meta[:version].match?(/\A\d/)
      vname = "#{meta[:name]}@#{meta[:version]}"
      files << build_output(meta, vname, keg_only: true)
    else
      warn "! #{meta[:name]} #{meta[:version]}: non-numeric version, no versioned formula"
    end
    files << build_output(meta, meta[:name], keg_only: false) if latest
    files
  end

  def build_output(meta, formula_name, keg_only:)
    body = formula_body(meta.merge(formula_name: formula_name, class: class_name(formula_name), keg_only: keg_only))
    { path: formula_path(formula_name), body: body }
  end

  def spdx(info)
    id = info.dig("license", "spdx_id")
    id if id && id != "NOASSERTION"
  end

  def run
    sources = JSON.parse(File.read(SOURCES))
    failures = []
    changed  = []

    sources.each do |source|
      repo  = source["repo"]
      metas = build_metas(source)
      metas.each_with_index do |meta, idx|
        outputs_for(meta, latest: idx.zero?).each do |file|
          old = File.exist?(file[:path]) ? File.read(file[:path]) : nil
          next if old == file[:body]

          FileUtils.mkdir_p(File.dirname(file[:path]))
          File.write(file[:path], file[:body])
          fname = File.basename(file[:path], ".rb")
          changed << "#{fname}: #{old ? "updated" : "(new)"} -> #{meta[:version]}"
          puts "* #{fname} #{old ? "updated" : "created"} -> #{meta[:version]} (#{meta[:platforms].size} platforms)"
        end
      end
    rescue => e
      # Skip this repo; its existing formulae are left untouched.
      warn "! #{repo}: #{e.message}"
      failures << repo
    end

    puts changed.empty? ? "\nNo formula changes." : "\nChanged:\n#{changed.map { |c| "  #{c}" }.join("\n")}"
    return if failures.empty?

    warn "\nFailed: #{failures.join(", ")}"
    exit 1
  end
end

SyncFormulae.run if __FILE__ == $PROGRAM_NAME
