title: ivuorinen/homebrew-tap
email: your-email@example.com
description: >-
  Homebrew Tap containing custom formulae for various tools and utilities.
  Automatically updated documentation for all available formulae.
baseurl: "/homebrew-tap"
url: "https://ivuorinen.github.io"
repository: ivuorinen/homebrew-tap

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  formulae:
    output: true
    permalink: /formula/:name/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "formulae"
    values:
      layout: "formula"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts/
  - .sass-cache/
  - .jekyll-cache/
